### ISSUE TITLE
What is the use of CNRs?

### ISSUE THREAD

**Issue by sascoms** [erasmus-without-paper/issues#43]
According to the specs, when you receive a CNR, you should directly return 200 (received) response.

However, what is the use of sending a CNR in the following scenario?

- PartnerA prepares an LA.
- PartnerA sends a CNR for this LA
- PartnerB system  receives CNR.
- PartnerB system  returns 200 response to PartnerA. (as specs states)
- PartnerB system  tries to fetch the LA.

- PartnerB system  receives error while fetching the LA from PartnerA
OR
- PartnerB system  receives LA but sees some errors in LA (XML validation or missing required information)

- PartnerB system does not show anything in HEIs screens and does not inform the IRO.

- However, PartnerA starts to wait for the LA approval/reject response from PartnerA as CNR was received.
- However, PartnerB does not even know they received a CNR for that LA.

**The LA approval process got stuck. (until the PartnerA asks PartnerB about the LA status via email or similar channel)**

Please can somebody tell us: What is the use of such CNR workflow in EWP data exchange?

This scenario and similar ones show that CNRs are useless if receiving partner can not display the LA or IIA in the IRO/HEI screens.

We should consider the rule of returning direct 200 response to CNRs for all cases.

This problem has two solutions:
A)
- If LA or IIA is not received or cannot be showed in HEI/IRO screens for some reasons, then CNR should receive non-200 error.
- If receiving system has internal problems in processing LA or IIA OR detects issues with the incoming LA or IIA, then it should NOT return 200. Instead it should return non-200 response. 

B)
1. Direct posting LA/IIA data to the partner. (PUSH method) (just as in the approval/rejection of LA)
This will remove the need for CNRs.

In fact, we think many APIs should use push method (direct posting of the data to the partner) and not CNRs.

**Comment by FrederikDejaeghereUGent** [comment]
Hello sascomms,

Exactly the opposite should happen. No push should be used. All the existing push methods should be removed because if a problem occurs the system cannot recover from it.

If an XML validation fails of course you will have to contact the other institution because the protocol was not respected. That's in any protocol.

It is possible that at some point the partner B cannot retrieve the LA from partner A (maintenance) even if the protocol was respected 100%.  Therefore you have to keep track of the CNR's you were not able to process so you can retry later. Because we use CNR's you are able to retry later. If this mechanism would not be in place you would really be stuck.

**Comment by BavoNootaert** [comment]
The pros and cons of CNRs vs only push have been discussed extensively here: https://github.com/erasmus-without-paper/ewp-specs-api-omobilities/issues/31
To summarize, it was and still is our position that to make a large heterogeneous system like EWP resilient, each node must be able to pull the applicable data from other nodes.
Of course bugs in an implementation need to be reported when discovered. There are appropriate channels for that. CNRs facilitate recovery from them.
